### ISSUE TITLE
❓ 请问如何正确配置代理服务器

### ISSUE THREAD

**Issue by rexcape** [zhaoolee/ptt_beauty_spider#1]
大佬你好，我是刚学会 `JavaScript` 基础知识的萌新，想借助本项目学习网络爬虫的用法，中国大陆的用户无法访问 `index.js` 中的网站，我有一个本地代理服务器（http://127.0.0.1:10809），想将代理服务器的配置添加到 `index.js` 中

我查找了 `download` 文档中的代理配置说明，[这是说明链接](https://www.npmjs.com/package/download#proxies)，说明中说其他选项和 `got` 是一样的，`got` 文档中说可以用 `tunnel` 包和 `agent` 选项来配置代理服务器，[这是文档链接](https://github.com/sindresorhus/got#proxies)，按照文档上的说明，在代码里面添加了 `const tunnel = require("tunnel");`，并将 `download_img` 的部分代码改为

```javascript
    await download(imgAndName["url"], path.join(__dirname, "images"), {
      filename: imgAndName["name"],
      agent: {
        https: tunnel.httpOverHttp({
          proxy: {
            host: "127.0.0.1",
            port: 10809,
          }
        })
      }
```

执行 `yarn start`，发现有错误：`下载出错==>> GotError [MaxRedirectsError]: Redirected 10 times. Aborting.`，请问大佬为什么会有这种错误，我应该如何正确配置代理服务器😭

**Comment by zhaoolee** [comment]
其实可以简单一些

你可以直接给终端配置代理
然后运行我的代码就可以了


如果你是mac,可以在运行代码前往终端输入

export http_proxy=http://127.0.0.1:10809

export https_proxy=http://127.0.0.1:10809

回车后，就可以愉快到执行我的代码了


如果你是windows 建议下载一个 gitbash,  https://gitforwindows.org/, 在gitbash
运行以上代码，也可以运行以上代码，走代理




mazixiang <notifications@github.com> 于2020年6月1日周一 下午1:08写道：

**Comment by rexcape** [comment]
大佬您好，感谢您抽出时间来回复我，我仔细阅读您的回复之后，查找一些资料，把我的 `git bash`、`powershell` 和 `cmd` 都挂上了代理，使用代理之前我运行之后是卡在第一章图片上的，最后报出超时（用 `npm` 和 `yarn` 是一样的结果）：

```bash
$ yarn start
yarn run v1.22.4
$ node index.js
https://beautyptt.cc/extend/?search=search&title=%E6%AD%A3%E5%A6%B9&author=&infinite_json&page=1
length::: 60
imgAndName:: { name: '[正妹] 恩星UJpom3E.jpg', url: 'https://i.imgur.com/UJpom3E.jpg' }
下载出错==>> GotError [RequestError]: connect ETIMEDOUT 31.13.79.1:443
    at ClientRequest.<anonymous>
```

用了代理后，脚本进行一段时间直接完成，没有任何下载：

```bash
$ yarn start
yarn run v1.22.4
$ node index.js
https://beautyptt.cc/extend/?search=search&title=%E6%AD%A3%E5%A6%B9&author=&infinite_json&page=1
==停止==
Done in 17.36s.
```

但是我用 Chrome 浏览器打开这个网页是有图片的，运行脚本之后有对应的请求，就是没有结果……我实在是查不出来是什么问题了😭😭

我的 `nodejs` 版本是 12.16.3，`Windows` 版本是 19635

**Comment by zhaoolee** [comment]
我刚刚在Win10试了一下,还是蛮正常的,不过我把package-lock.json删了,
你可以只保留index.js和package.json,然后npm install 然后 node
index.js试试,如果还不行,应该是你的VPN设置有问题



可以加我微信 jianzhao111

mazixiang <notifications@github.com> 于2020年6月1日周一 下午5:02写道：

**Comment by rexcape** [comment]
收到，感谢您耐心为我解答
